// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1kMyWLs1q95h-kJ8HTL_9Fe3T7Nxl5c',
    appId: '1:171478697751:android:f03031f9b94f4c35cdd952',
    messagingSenderId: '171478697751',
    projectId: 'nss-vhss',
    databaseURL: 'https://nss-vhss-default-rtdb.firebaseio.com',
    storageBucket: 'nss-vhss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ4pYaR8h5ROsMyhgIWnmH6eOXkcETcOA',
    appId: '1:171478697751:ios:d7e5c2c4a28be4fccdd952',
    messagingSenderId: '171478697751',
    projectId: 'nss-vhss',
    databaseURL: 'https://nss-vhss-default-rtdb.firebaseio.com',
    storageBucket: 'nss-vhss.appspot.com',
    iosClientId: '171478697751-nm3kcrta9s841u10bshe28ifo9fir53i.apps.googleusercontent.com',
    iosBundleId: 'nss.sunrise.in',
  );
}
